config/routes.rb
Calendar::Application.routes.draw do
 
 match '/ECE' => 'mains#ece'
 match '/course_description/:id' => 'courses#course_description'
 match '/like_d_thread/:userId/:dThreadId/:vote' => 'd_threads#like_d_thread'
 match '/like_d_thread_reply/:d_thread_id/:userId/:replyId/:vote' => 'replies#like_reply'
 match 'chat/display', :to=> 'chats#chat_display'
  match 'chat/update', :to => 'chats#chat_update'
  match 'chat/message', :to => 'chats#chat_message', :via => :post
 
 resources :eces

	
  match 'd_threads/post' => 'd_threads#post'
	
  resources :courses
  resources :d_threads do
  	resources :replies
  end
  resources :tags
  
  resources :allcourses

  resources :courses
  match '/check_course', :to => 'courses#course'
  match '/check_tag', :to => 'd_threads#tag'
  match '/ece', :to => 'eces#ece'
  match '/ece/', :to => 'eces#ece'
  
  resources :events

  get "calendar/index"

  match '/calendar', :to => 'calendar#index'
   resources :supports, :only => [:new, :create]

resources :users do
    member do
      get :following, :followers
    end
  end
  resources :users
  resources :sessions, :only => [:new, :create, :destroy]
  resources :relationships, :only => [:create, :destroy]
  match '/search', :to => 'users#index'
    match '/qsearch', :to => 'd_threads#search'
  match '/contactus',:to => 'supports#new'
  match '/signin' , :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'
  match '/sign_up', :to => 'users#new'
  match '/contact', :to => 'pages#contact'
  match '/about'  , :to => 'pages#about'
  match '/help'   , :to => 'pages#help'
  root :to => 'pages#home'

  

end

app/models/ece.rb
class Ece < ActiveRecord::Base
	validates :course_code, :uniqueness => true
	
	acts_as_simply_searchable :columns => :name

	
end

app/controllers/eces_controller.rb
class EcesController < ApplicationController
  # GET /eces
  # GET /eces.xml
  def index
    @eces = Ece.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @eces }
    end
  end

  def course

    @courses = Ece.all
    @a = "#{params[:course]}"
    $b = Ece.find_by_course_code("#{params[:course]}")



    unless $b.nil? || $b == 0
 	    @c = $b.id
    @path  = "#{root_path}"+"eces/" + "#{@c}"
      @title = "Courses"
      redirect_to @path
    end
  end

	def ece
		@title="ECE"
	end
 

  # GET /eces/1
  # GET /eces/1.xml
  def show
    @ece = Ece.find(params[:id])
    @path = Course.where(:courseCode => @ece.course_code).first   #don't check if nil, because if nil, link doesn't work and no error 
=begin
    @course=Course.all
    if !$b.nil?
    @ccc=$b.course_code
    @path = "/courses/#{Course.find_by_courseCode(@ccc).id}"
    end
=end
    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @ece }
    end
  end

  # GET /eces/new
  # GET /eces/new.xml
  def new
    @ece = Ece.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @ece }
    end
  end

  # GET /eces/1/edit
  def edit
    @ece = Ece.find(params[:id])
  end

  # POST /eces
  # POST /eces.xml
  def create
    @ece = Ece.new(params[:ece])

    respond_to do |format|
      if @ece.save
        format.html { redirect_to(@ece, :notice => 'Ece was successfully created.') }
        format.xml  { render :xml => @ece, :status => :created, :location => @ece }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @ece.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /eces/1
  # PUT /eces/1.xml
  def update
    @ece = Ece.find(params[:id])

    respond_to do |format|
      if @ece.update_attributes(params[:ece])
        format.html { redirect_to(@ece, :notice => 'Ece was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @ece.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /eces/1
  # DELETE /eces/1.xml
  def destroy
    @ece = Ece.find(params[:id])
    @ece.destroy

    respond_to do |format|
      format.html { redirect_to(eces_url) }
      format.xml  { head :ok }
    end
  end
end

app/views/eces/_form.html.erb
<%= form_for(@ece) do |f| %>
  <% if @ece.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ece.errors.count, "error") %> prohibited this ece from being saved:</h2>

      <ul>
      <% @ece.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>

  <div class="field">
    <%= f.label :course_code %><br />
    <%= f.text_field :course_code %>
  </div>

  <div class="field">
    <%= f.label :Area %><br />
    <%= f.text_field :Area %>
  </div>
  <div class="field">
    <%= f.label :Prerequisites %><br />
    <%= f.text_field :Prerequisites %>
  </div>
  <div class="field">
    <%= f.label :Lecturehours %><br />
    <%= f.text_field :Lecturehours %>
  </div>
  <div class="field">
    <%= f.label :Labhours %><br />
    <%= f.text_field :Labhours %>
  </div>
  <div class="field">
    <%= f.label :Tutorialhours %><br />
    <%= f.text_field :Tutorialhours %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/eces/course.html.erb
<h1> How to search courses </h1>
<h4>Please enter a valid course name </h4>
<p> The letters should be lowercase followed by numbers </br> For example: ece361<p>

<h1> @course is <%= @course %></h1>
<h1> @a is <%= @a %></h1>
<h1> @b is <%= @b %></h1>
<h1> @c is <%= @c %></h1>
<h1>@path is <%= @path%></h1>

app/views/eces/ece.html.erb
<% form_tag check_course_path, :method => 'get' do %>
<p>
    <%= text_field_tag :course, params[:course] %>
    <%= submit_tag "Go To Course", :name => nil %>
<br />
    example: ECE361
</p>
  <% end %>


<h1>ECE @ uoft</h1>
<table>
  <tr>
    <th>Website</th>
    <th>Undergraduate office</th>
    <th>Email</th>
    <th>Phone</th>
  </tr>

  <tr>
    <td> <a href="http://www.ece.utoronto.ca/">www.ece.utoronto.ca/</td>
    <td> Room SFB600</td>
    <td>askece@ecf.utoronto.ca</td>
    <td>416-978-0488</td>
  </tr>
</table>



<p>The following ece courses provide discussion forums, course ratings, comments/suggestions from previous students, past papers and chat rooms. </br>
Please visit a specific course for more details </p>


app/views/eces/edit.html.erb
<h1>Editing ece</h1>

<%= render 'form' %>

<%= link_to 'Show', @ece %> |
<%= link_to 'Back', eces_path %>

app/views/eces/index.html.erb
<h1>Listing eces</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th>Course code</th>
    <th>Area</th>
    <th>Prerequisites</th>
    <th>Lecturehours</th>
    <th>Labhours</th>
    <th>Tutorialhours</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @eces.each do |ece| %>
  <tr>
    <td><%= ece.name %></td>
    <td><%= ece.description %></td>
    <td><%= ece.course_code %></td>
    <td><%= ece.Area %></td>
    <td><%= ece.Prerequisites %></td>
    <td><%= ece.Lecturehours %></td>
    <td><%= ece.Labhours %></td>
    <td><%= ece.Tutorialhours %></td>
    <td><%= link_to 'Show', ece %></td>
    <td><%= link_to 'Edit', edit_ece_path(ece) %></td>
    <td><%= link_to 'Destroy', ece, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Ece', new_ece_path %>

app/views/eces/new.html.erb
<h1>New ece</h1>

<%= render 'form' %>

<%= link_to 'Back', eces_path %>

app/views/eces/show.html.erb
<p id="notice"><%= notice %></p>
<h1>
  <%= @ece.name %>
</h1>
<p>
  <b>Description:</b>
  <%= @ece.description %>
</p>


<table>
  <tr>
    <th>Area</th>
    <th>Prerequisites</th>
    <th>Lecturehours</th>
    <th>Labhours</th>
    <th>Tutorialhours</th>
  </tr>

  <tr>
    <td><%= @ece.Area %></td>
    <td><%= @ece.Prerequisites %></td>
    <td><%= @ece.Lecturehours %></td>
    <td><%= @ece.Labhours %></td>
    <td><%= @ece.Tutorialhours %></td>
  </tr>
</table>
<p> Comments: </p>



<p><%= link_to "Forum"  , "#{root_path}"+"eces/" + "#{@ece.id}", :class=>"question_button round" %>

<h3>Note: The above information was taken from www.magellan.ece.utoronto.ca</h3>


<%= link_to 'Edit', edit_ece_path(@ece) %> |
<%= link_to 'Back', eces_path %>