config/routes.rb
Calendar::Application.routes.draw do
 
 match '/ECE' => 'mains#ece'
 match '/course_description/:id' => 'courses#course_description'
 match '/like_d_thread/:userId/:dThreadId/:vote' => 'd_threads#like_d_thread'
 match '/like_d_thread_reply/:d_thread_id/:userId/:replyId/:vote' => 'replies#like_reply'
 match 'chat/display', :to=> 'chats#chat_display'
  match 'chat/update', :to => 'chats#chat_update'
  match 'chat/message', :to => 'chats#chat_message', :via => :post
 
 resources :eces

	
  match 'd_threads/post' => 'd_threads#post'
	
  resources :courses
  resources :d_threads do
  	resources :replies
  end
  resources :tags
  
  resources :allcourses

  resources :courses
  match '/check_course', :to => 'courses#course'
  match '/check_tag', :to => 'd_threads#tag'
  match '/ece', :to => 'eces#ece'
  match '/ece/', :to => 'eces#ece'
  
  resources :events

  get "calendar/index"

  match '/calendar', :to => 'calendar#index'
   resources :supports, :only => [:new, :create]

resources :users do
    member do
      get :following, :followers
    end
  end
  resources :users
  resources :sessions, :only => [:new, :create, :destroy]
  resources :relationships, :only => [:create, :destroy]
  match '/search', :to => 'users#index'
    match '/qsearch', :to => 'd_threads#search'
  match '/contactus',:to => 'supports#new'
  match '/signin' , :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'
  match '/sign_up', :to => 'users#new'
  match '/contact', :to => 'pages#contact'
  match '/about'  , :to => 'pages#about'
  match '/help'   , :to => 'pages#help'
  root :to => 'pages#home'

  

end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  # GET /courses
  # GET /courses.xml
  def index
    @courses = Course.all
		
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @courses }
    end
  end

  # GET /courses/1
  # GET /courses/1.xml
  def show
    @c = @course = Course.find(params[:id])
		@t = DThread.where(:courseCode => @c.courseCode)
		@t = @t.sort! { |a,b| a.created_at <=> b.created_at }
		@t = @t[0..4] #Have 5 last published
		#@current_C = current_course
		 
    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @course }
    end
  end

    def course

    @courses = Course.all
    @a = "#{params[:course]}"
    $b = Course.find_by_courseCode("#{params[:course]}")

    if $b.nil?
	$b = Course.find_by_courseCode("#{params[:course]}"+"H1")
    elsif $b.nil?
	$b = Course.find_by_courseCode("#{params[:course]}"+"Y1")
    end 
   unless $b.nil? || $b == 0
 	    @c = $b.id
  
    @path  = "#{root_path}"+"courses/" + "#{@c}"
      @title = "Courses"
      redirect_to @path
    end
  end


#Rest of the actions are useless, since user can't add/remove courses

  # GET /courses/new
  # GET /courses/new.xml
  def new
    @course = Course.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @course }
    end
  end

  # GET /courses/1/edit
  def edit
    @course = Course.find(params[:id])
  end

  # POST /courses
  # POST /courses.xml
  def create
    @course = Course.new(params[:course])

    respond_to do |format|
      if @course.save
        format.html { redirect_to(@course, :notice => 'Course was successfully created.') }
        format.xml  { render :xml => @course, :status => :created, :location => @course }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @course.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /courses/1
  # PUT /courses/1.xml
  def update
    @course = Course.find(params[:id])

    respond_to do |format|
      if @course.update_attributes(params[:course])
        format.html { redirect_to(@course, :notice => 'Course was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @course.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /courses/1
  # DELETE /courses/1.xml
  def destroy
    @course = Course.find(params[:id]) 
    @course.destroy

    respond_to do |format|
      format.html { redirect_to(courses_url) }
      format.xml  { head :ok }
    end
  end
  
  def course_description
  	@c = Course.where(:courseCode =>(params[:id])).first 
  	Course.column_names.each do |n| #replace all nil fields with '-'
  		@c[n] = "-" unless @c[n] 
  	end
  	@areaNames = []
  	if @c.discipline =='ECE'
  		@areaNames <<'Area 1: Photonics & Semiconductor Physics' <<'Area 2: Electromagnetics & Energy Systems' << 'Area 3: Analog and Digital Electronics' <<'Area 4: Control, Communication & Signal Processing' << 'Area 5: Computer Hardware & Computer Networks' << 'Area 6: Software'<<'Area 7: Science/Math'
  	end 
  	respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @course }
    end
  end
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/views/courses/_form.html.erb
<%= form_for(@course) do |f| %>
  <% if @course.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@course.errors.count, "error") %> prohibited this course from being saved:</h2>

      <ul>
      <% @course.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/courses/course.html.erb
<h1> How to search courses // courses</h1>
<h4>Please enter a valid course name </h4>
<p> The letters should be lowercase followed by numbers </br> For example: ece361<p>

<h1> @course is <%= @course %></h1>
<h1> @a is <%= @a %></h1>
<h1> $b is <%= $b %></h1>
<h1> @c is <%= @c %></h1>
<h1>@path is <%= @path%></h1>

app/views/courses/course_description.html.erb
<h1><%= "#{@c.courseCode} #{@c.session} #{@c.title}" %></h1>

<table>
	<tr>
		<th>Course Title :</th>
		<th><%=  "#{@c.courseCode} #{@c.session} #{@c.title}" %></th>   
	</tr>
		
	<% if @areaName %>
		<tr> 
			<th>Area(s): </th>
			<% if @c.area > 7 %>
				<th> <table> 
					<% for r in 0..-1 + @c.area.to_s.size %>						
						<tr><th> 
							<%= areaNames[Integer(@c.area.to_s.scan(/./)[r])] %>
						</th></tr>
					<%end%> 
				</table> </th> 
			<% else %>
				<th> <%= areaNames[1 + @c.area] %> </th>
			<% end %>
		</tr>
	<%end%>
	
	<tr> 
		<th>Prerequisites :</th>   
		<th><%= @c.prerequisites %></th>
	</tr>
		
	<tr> 
		<th>Co-requisites :</th>  
		<th><%= @c.corequisites %></th>
	</tr>	
	
	<tr>
		<th> Hours : </th>
		<th> 
			<table>
				<tr>
					<th> Lecture Hours </th>
					<th> Lab Hours </th>
					<th> Tutorial Hours </th>
				</tr>
				<tr>
					<th> <%= @c.lectureHours %></th>
					<th> <%= @c.labHours %></th>
					<th> <%= @c.tutorialHours %></th>
				</tr>
			</table>
		</th>	
	</tr> 
	
	<tr>
		<th width = 100> Description : </th>
		<th> <%= @c.description %> </th>
	</tr>
</table>

app/views/courses/edit.html.erb
<h1>Editing course</h1>

<%= render 'form' %>

<%= link_to 'Show', @course %> |
<%= link_to 'Back', courses_path %>

app/views/courses/index.html.erb
<h1>Discussion Board</h1>

<table>
  <tr>
    <th>Courses</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @courses.each do |course| %>
  <tr> 
    <td><%= link_to course.title, course %></td>
    <td><%= "Course code is: #{course.courseCode} "  %></td> 
  </tr>
<% end %>
</table>

<br />

<% link_to 'New Course', new_course_path %>

app/views/courses/new.html.erb
<h1>New course</h1>

<%= render 'form' %>

<%= link_to 'Back', courses_path %>

app/views/courses/show.html.erb
<p id="notice"><%= notice %></p>

<h1> <%= "#{@c.courseCode} : #{@c.title}" %> </h1>
</br>


<p> <% link_to "Back", '/years/' %> </p>
<p> <% link_to "Back to course list", '/courses' %> </p>

<% link_to 'Edit', edit_course_path(@course) %> 

<h3> Some Apps Here </h3>
<h3> Rate the Prof/course here </h3>
		
<p><%= link_to "Calendar Description: #{@c.description[0..99]}...", "/course_description/#{@c.courseCode}" %></p>
<p><%= "Anti-description : #{@c.antiDescription}" %></p>	

<h1> Questions: </h1>		
<hr></hr>
</br>
<p> <%= link_to 'New Question', new_d_thread_path, :class=>"link_button round"  %> </p>

<h4> Top 5 most recents threads displayed here </h4>
	<% @t.reverse.each do |t| %>
		<h3>  
  	<td><%= link_to t.title, t %></td>
  			<% if t.question.size > 120 %>
  			<% 		@dispQ = t.question[0..100] + '...' %> 
  			<% else @dispQ = t.question %>  	
  			<% end %>					
  	<td>      <%= @dispQ %></td> 
		</h3>
<hr></hr>
		
  <% end %>	