config/routes.rb
Calendar::Application.routes.draw do
 
 match '/ECE' => 'mains#ece'
 match '/course_description/:id' => 'courses#course_description'
 match '/like_d_thread/:userId/:dThreadId/:vote' => 'd_threads#like_d_thread'
 match '/like_d_thread_reply/:d_thread_id/:userId/:replyId/:vote' => 'replies#like_reply'
 match 'chat/display', :to=> 'chats#chat_display'
  match 'chat/update', :to => 'chats#chat_update'
  match 'chat/message', :to => 'chats#chat_message', :via => :post
 
 resources :eces

	
  match 'd_threads/post' => 'd_threads#post'
	
  resources :courses
  resources :d_threads do
  	resources :replies
  end
  resources :tags
  
  resources :allcourses

  resources :courses
  match '/check_course', :to => 'courses#course'
  match '/check_tag', :to => 'd_threads#tag'
  match '/ece', :to => 'eces#ece'
  match '/ece/', :to => 'eces#ece'
  
  resources :events

  get "calendar/index"

  match '/calendar', :to => 'calendar#index'
   resources :supports, :only => [:new, :create]

resources :users do
    member do
      get :following, :followers
    end
  end
  resources :users
  resources :sessions, :only => [:new, :create, :destroy]
  resources :relationships, :only => [:create, :destroy]
  match '/search', :to => 'users#index'
    match '/qsearch', :to => 'd_threads#search'
  match '/contactus',:to => 'supports#new'
  match '/signin' , :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'
  match '/sign_up', :to => 'users#new'
  match '/contact', :to => 'pages#contact'
  match '/about'  , :to => 'pages#about'
  match '/help'   , :to => 'pages#help'
  root :to => 'pages#home'

  

end

app/models/d_thread.rb
class DThread < ActiveRecord::Base
#DThread has members: title, id , course_id, author, question, courseCode, created_at, updated_at
	
	validates :title, :presence => true, 
										:length => {:within => 1..100}
	
	validates :question, :presence => true,
											 :uniqueness => true
											  
	validates :courseCode, :presence => true, 
											 	 :format => { :with => /[a-zA-Z]+[a-zA-Z]+[a-zA-Z]+[1-5]+[0-9]{2}/i }  #regex for course code of the form 'ece216'
	
#	validate :course_exists
	validate :verify_course
	
	belongs_to :course
	has_many :replies
	has_many :tags
	belongs_to :user
	has_many :d_thread_ratings
	 
	before_save :verify_course , :verify_tags, :verify_user
	after_save	:create_tags
	
	def verify_course
		course_code = self.courseCode
		if c = Course.where(:courseCode => course_code)[0] 
			self.course_id = c.id
			return true
		elsif course_code.size == 6
			if c = Course.where(:courseCode => course_code + 'H1')[0] 
				self.course_id = c.id
				self.courseCode = course_code + 'H1'
				return true
			elsif c = Course.where(:courseCode => course_code + 'Y1')[0] 
				self.course_id = c.id
				self.courseCode = course_code + 'Y1'
				return true
			end
		elsif course_code.size == 8
			if c = Course.where(:courseCode => course_code[0..-3])[0]
				self.course_id = c.id
				self.courseCode = course_code[0..-3]
				return true
			end
		end
		errors.add(:courseCode, "Course #{courseCode} doesn't exist") 
		return false
	end
	

	def verify_tags
		if self.tg  #BUG, SHOULD NOT NEED THIS IF STATEMENT
			tags = self.tg.split(/[\s,;]/) #verify number of , and appropriateness of tags	
			if tags.size == 0
				errors.add(:tg, "No tags")
				return false
			elsif tags.size > 5
				errors.add(:tg, "Too many tags") 
				return false
			else
				tags.each do |t|				
					if t =~ /[^0-9a-zA-Z+-_]/
						errors.add(:tags, "Inappropriate Tag") 
						return false
					end	
				end
			end		
			return true
		end
		else 
			return false
	end
	
	def create_tags
		tags = self.tg.split(/[\s,;]/) #don't need to do any error checking - done in verify_tags
		tags.each do |t|
		  Tag.create(:name => t, :d_thread_id => self.id) unless t == ""
		end
	end
	
	def verify_user
    if $glo#@currentUser#||= User.authenticate_with_salt(*remember_token)
    	self.user_id = $glo
		else
			errors.add(:user_id, "User not verified")
			return false
		end
	end
	
=begin
    def user_from_remember_token
      User.authenticate_with_salt(*remember_token)
    end
=end	

end

app/controllers/d_threads_controller.rb
class DThreadsController < ApplicationController

	def index
    @t = DThread.all
    @d_threads = DThread.paginate(:page => params[:page])
		
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @d_threads }
    end
  end
  
  
  # GET /d_threads/1
  # GET /d_threads/1.xml
  def show
    @t = DThread.find(params[:id])
    @id = @t.user_id
    @uss = User.find_by_id("#{@id}") 				
		@crs = 	Course.find_by_courseCode(@t.courseCode)
		@path = ''
		@tg = Tag.where(:d_thread_id => @t.id)
		$CURRENT_DTHREAD = @t.id
		@u = $CURRENT_USER
		
		if @crs
			@path = '/courses/' + @crs.id.to_s() 
    else
    	@path = '/courses/'
    end
    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @d_thread }
    end
  end
	
	def like_d_thread
		@d = DThread.where(:id => params[:dThreadId]).first	#hashes defined in route for method
		if @rating = DThreadRating.where("user_id = ? AND d_thread_id = ?", params[:userId] , @d.id).first 
			@rating.likes = 1 if params[:vote] == 'like' 	  
			@rating.likes = -1 if params[:vote] == 'dislike'  
			@rating.save  
	
		else  	
			if params[:vote] == 'like'  
				@d.d_thread_ratings.create(:likes => 1, :user_id => params[:userId])  
			elsif params[:vote] == 'dislike'  
				@d.d_thread_ratings.create(:likes => -1, :user_id => params[:userId])		   
			end  
		end  
			redirect_to :back, :notice => "#{params[:vote]}d"	
	end
			
			
	def search
	 $result = DThread.where("title like ? OR question like ?", "%" + params[:query] + "%", "%" + params[:query] + "%") 
	end
	
	def new
		respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @d_thread }
    end		
  end

	def post
		@t = DThread.new
    respond_to do |format|
      format.html # post.html.erb
      format.xml  { render :xml => @d_thread }
    end
	end
	
	# GET /d_threads/1/edit
  def edit
    @t = DThread.find(params[:id])
  end

  # POST /d_threads
  # POST /d_threads.xml
  def create
    @t = DThread.new(params[:d_thread])

    respond_to do |format|
      if @t.save
        format.html { redirect_to(@t, :notice => 'Thread was successfully created.') }
        format.xml  { render :xml => @t, :status => :created, :location => @t }
      else
        format.html { render :action => "post" }
        format.xml  { render :xml => @t.errors, :status => :unprocessable_entity }
      end
    end
  end

	def tag

    @a = "#{params[:course]}"
    @tt = Tag.find_by_name("#{params[:course]}")

   unless @tt.nil? || @tt == 0
 	    @c = @tt.id
    @path  = "#{root_path}"+"tags/" + "#{@c}"
      @title = "Tags"
      redirect_to @path
    end
  end
	
	
  # PUT /d_threads/1
  # PUT /d_threads/1.xml
  def update
    @t = DThread.find(params[:id])

    respond_to do |format|
      if @t.update_attributes(params[:d_thread])
        format.html { redirect_to(@course, :notice => 'Course was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @t.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /d_threads/1
  # DELETE /d_threads/1.xml
  def destroy
    @t = DThread.find(params[:id])
    @t.destroy

    respond_to do |format|
      format.html { redirect_to(courses_url) }
      format.xml  { head :ok }
    end
  end

end

app/helpers/d_threads_helper.rb
module DThreadsHelper


  def sign_in(user)
    cookies.permanent.signed[:remember_token] = [user.id, user.salt]
    self.current_user = user
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user
    @current_user ||= user_from_remember_token
  end

  def signed_in?
    !current_user.nil?
  end
  
  def current_user?(user)
    user == current_user
  end

  def authenticate
    deny_access unless signed_in?
  end


  def deny_access
    store_location
    redirect_to signin_path, :notice => "Please sign in to access this page."
  end

  def sign_out
    cookies.delete(:remember_token)
    self.current_user = nil
  end

  def redirect_back_or(default)
    redirect_to(session[:return_to] || default)
    clear_return_to
  end

  private

    def user_from_remember_token
      User.authenticate_with_salt(*remember_token)
    end

    def remember_token
      cookies.signed[:remember_token] || [nil, nil]
    end

    def store_location
      session[:return_to] = request.fullpath
    end

    def clear_return_to
      session[:return_to] = nil
    end


end

app/views/d_threads/_d_thread.html.erb
<%= div_for d_thread do %>
  <h3>
    <%= link_to d_thread.title, d_thread %>
    <span class='actions'>
      <%= link_to "Edit", edit_d_thread_path(article) %>
      <%= link_to "Delete", d_thread, :confirm => "Are you sure?", :method => :delete %>
    </span>
  </h3>
  <%= d_thread.body %>
<% end %>

app/views/d_threads/_form.html.erb
<%= form_for(@t) do |f| %>
  
  <% if @t.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@t.errors.count, "error") %> prohibited this course from being saved:</h2>

      <ul>
      <% @t.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  
   <div class="field">
    <%= f.label :question %><br />
    <%= f.text_field :question %>
  </div>
  
   <div class="field">
    <%= f.label :Course_Code %><br />
    <%= f.text_field :courseCode %>
  </div>
  
  <% if @currentUser = current_user %>
		<%= "Author : #{current_user.name} "%>
		<%= @t.user_id = current_user.id %>
		
	<%else%>
		<div class="field">
		  <%= f.label :author %><br />
		  <%= f.text_field :author %>
			<%= link_to 'Login / Sign-up' , '/years/' %>
		</div>
	<% end %> 
 <div class="field">
    <%= f.label :tags %> <%= "(atleast 1, atmost 5; use ',' ';' or ' ' as delimiters )" %> <br />
    <%= f.text_field :tg %>
  </div>
 
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/d_threads/edit.html.erb
<h1>Editing Thread</h1>

<%= render 'form' %>

<%= link_to 'Show', @t %> |
<%= link_to 'Back', d_threads_path %>

app/views/d_threads/index.html.erb
<h1>Discussion Board</h1>

<h4> <%= link_to 'Tags', '/tags' %> </h4>
<%= will_paginate %>
<% @t.reverse.each do |t| %>


<table><tr><td>
	<h4> Title: <%= link_to t.title, t %>  </br>
	<strong> Question:  <%= t.question[0..50] %></strong>  </h4>	 
	
	<h4>Tags:<% Tag.where(:d_thread_id => t.id).each do |tg| %>
		 <%= link_to "#{tg.name}" , tg %> </h4> 
	<% end %>
<h3>	<%= t.courseCode %> 
	<%= t.author if t.author %>
	</h3>
	<% if Time.now - t.created_at > 3600 %> 
	
		Posted on <%= t.created_at.strftime("%A, %B %d") if t.created_at %>
by
	<% else %>
		Posted <%= ((Time.now - t.created_at)/60).to_i %> minutes ago
 by 
<% @u = User.find_by_id("#{t.user_id}") %>

<% logo = image_tag(gravatar_for @u, :alt => "Sample App", :class => "round") %> 
        <%= gravatar_for @u %>
	  <%= link_to logo, @u %>


	<% end %>
		</td></tr></table>
	<br />
<% end %>


<%= will_paginate %>

app/views/d_threads/new.html.erb
<% if current_user %>

	<h2> Rules:</h2>
<h2>What rules should we have?</h2>

<%= link_to "Continue", href="/d_threads/post", :class=>"signup_button round" %>

<% else %>
	
	<font color="red">You must be a registered user to ask questions </font> 
	<p> <%= link_to 'Sign Up', sign_up_path %> </p>
	<p> <%= link_to 'Login-in', signin_path %> </p>

<%end%>

app/views/d_threads/post.html.erb
<h1>New Question</h1>

<%= render 'form' %>

<%= link_to "Back to Discussion Board", '/d_threads/' %>

app/views/d_threads/search.html.erb
<h1> Results Found </h1>

<% $result.each do |r| %>
	<%= link_to "#{r.title}", r %>
	<%= r.question %>
	</br>  
<% end %>

app/views/d_threads/show.html.erb
<p id="notice"><%= notice %></p>
<%= link_to "Ask Question!", href="/d_threads/new", :class=>"question_button round" %></br></br>
<h1><strong><%= @t.title %>  </strong></h1>
<hr></hr>
</br>
<h3>	<%= @t.question %>   </h3>

<h4> Tags: 
<% @tg.each do |tg| %>
	<%= link_to tg.name, tg %>
<%end %>	
</h4>
      <h1>
	  <% logo = image_tag(gravatar_for @uss, :alt => "Sample App", :class => "round") %> 
        <%= gravatar_for @uss %>
	  <%= link_to logo, @uss %></h1>
	<h4> <strong><%=@uss.name%></strong></h4>


<% if signed_in? %>
	<h3> 
		<%= link_to 'Like', "/like_d_thread/#{current_user.id}/#{@t.id}/like" %> 
		<%= link_to 'Dislike', "/like_d_thread/#{current_user.id}/#{@t.id}/dislike" %>
	</h3>
<%end%>

<% @likes = @dislikes = 0 %>
<% @t.d_thread_ratings.each do |d| %>
	<% @likes +=1 if d.likes == 1 %> 
	<% @dislikes +=1 if d.likes == -1 %>
<% end %> 

<h3> <%="Likes : #{@likes}, Dislikes : #{@dislikes}"%> </h3>




</br></br>
<h3> Replies: </h3>
<div id = "replies">
<h3>	<%= render @t.replies %></h3>
</div>

<%= render :file => 'replies/new' %>

<% link_to "new reply", new_d_thread_reply_path(@t, :format => :js), :remote => true, :id => 'new_reply_link' %>


<p>
		<% if current_user || $CURRENT_USER %>
			<%= link_to 'Edit', edit_d_thread_path(@t) %> <%= edit_d_thread_path(@t) %>  
		<% end %>
		<br \>
		<%= link_to 'Back to Discussion Board', d_threads_path %>   		
		<%= link_to "Back to #{@crs.discipline}", "/#{@crs.discipline}/" %>
		<%= link_to "Back to #{@crs.title}", @path %> 
</p>

		

		

app/views/d_threads/tag.html.erb
<h1> How to search courses </h1>
<h4>Please enter a valid course name </h4>
<p> The letters should be lowercase followed by numbers </br> For example: ece361<p>

<h1> @course is <%= @course %></h1>
<h1> @a is <%= @a %></h1>
<h1> @b is <%= @b %></h1>
<h1> @c is <%= @c %></h1>
<h1>@path is <%= @path%></h1>